### ISSUE TITLE
ImportError: No module named pathos.multiprocessing

### ISSUE THREAD

**Issue by ethicalhack3r** [darryllane/Bluto#1]
I have 'old' Bluto installed and wanted this new one:

Ran the following to install:
`$ sudo pip install git+git://github.com/darryllane/Bluto`

Tried to run bluto:

```
$ bluto
Traceback (most recent call last):
  File "/usr/local/bin/bluto", line 22, in <module>
    from modules.get_dns import action_brute_start, action_wild_cards, action_zone_transfer, get_dns_details, action_brute_wild
  File "/Library/Python/2.7/site-packages/Bluto/modules/get_dns.py", line 13, in <module>
    from pathos.multiprocessing import ProcessingPool
ImportError: No module named pathos.multiprocessing
```

Tried to install the missing dependency:

`$ sudo pip install pathos`

Still same error when running bluto.

**Comment by darryllane** [comment]
This was a redundant module from dev stage. It has been removed along with dill. Uninstall and reinstall should now work.

**Comment by darryllane** [comment]
Is this working for you now?
