### ISSUE TITLE
Manual Install

### ISSUE THREAD

**Issue by ap0l0** [darryllane/Bluto#10]
I am getting this error. Can I use bluto without full installation?

root@ubuntu:~/Bluto# python Bluto/bluto
Traceback (most recent call last):
  File "Bluto/bluto", line 14, in <module>
    FILENAME_1 = path + "/Bluto/doc/subdomains-top1mil-20000.txt"
NameError: name 'path' is not defined
root@ubuntu:~/Bluto#

**Comment by darryllane** [comment]
Hi, can you explain your install process (as you carried it out).

**Comment by darryllane** [comment]
Not had a response to this so will be closing it unless you can get back to me?
