### ISSUE TITLE
Scan hanging at Gathering doc

### ISSUE THREAD

**Issue by erwanlr** [darryllane/Bluto#15]
Since a while, Bluto doesn't really work anymore for me. It just hangs at the Gathering doc part but never finishes and has to be killed. So no results displayed.

Doesn't seem to be related to the scanned domain and the originating IP (I used mine and a proxy, along with different domains).

Edit: Latest stable version used (2.4.5), on macOS Sierra and Ubuntu

**Comment by erwanlr** [comment]
Well, it's working again. So it might be specific to some domains after all.

**Comment by darryllane** [comment]
Ok, thanks for letting me know, it could be domain specific. I am currently doing a rewrite which is on hold until i get the oscp out the way. Ill take a quick look tonight at the module specifically hopefully its something obvious. Could you dm me a domain you had probs with?

**Comment by erwanlr** [comment]
Fixed, but you messed up the commit message to close it ;P

**Comment by darryllane** [comment]
Haha oops,

**Comment by darryllane** [comment]
It was specific to domains that didnt return a list of documents (downloadable documents, logic flaw)
