### ISSUE TITLE
subdomains-top1mil-20000.txt contains char-strings ending with dot

### ISSUE THREAD

**Issue by sagarbelure** [darryllane/Bluto#16]
There are plenty of char-strings in subdomains-top1mil-20000.txt, those end with '.' character, making them invalid while resolving. One such example would be -

`host: 'a.ns.emailvision.net..example.com' is not a legal name (empty label)`

There are 24 such entries as follows -
$ grep '[.]$' subdomains-top1mil-20000.txt 
a.ns.emailvision.net.
b.ns.emailvision.net.
c.ns.emailvision.net.
d.ns.emailvision.net.
dns1.freshegg.net.
easydns1.dualtec.com.br.
easydns2.dualtec.com.br.
ferrari.fortwayne.com.
jordan.fortwayne.com.
m.
mail.
ns-1.open.ro.
ns-2.open.ro.
ns-3.open.ro.
ns1.simpleviewinc.com.
ns1.twtelecom.net.
ns1.viviotech.net.
ns2.cl.bellsouth.net.
ns2.simpleviewinc.com.
ns2.twtelecom.net.
ns2.viviotech.net.
ns3.cl.bellsouth.net.
pns.dtag.de.
quatro.oweb.com.

**Comment by sagarbelure** [comment]
Doesn't really look like just the subdomain entries though.

**Comment by darryllane** [comment]
Thanks for pointing it out ill take a look. I am moving away from that list to a new improved one but will make sure i amend the current one.

Take a look at the dev branch if you're interested.
