### ISSUE TITLE
error since update

### ISSUE THREAD

**Issue by truesamurai** [darryllane/Bluto#26]
I did update today and now I have this error with every domain I try:

Error: 
Domain Not Valid, Check You Have Entered It Correctly

**Comment by darryllane** [comment]
Did you update via pip?

sudo pip install bluto --upgrade

**Comment by truesamurai** [comment]
I tried with another domain and now it is working.
The first domain which did not work was behind Cloudflare.

**Comment by darryllane** [comment]
Odd, Ive used it on CloudFlare hosted DNS quite a few times. But glad its working now. Thanks for the update

**Comment by truesamurai** [comment]
Do all domain names work? The one that is not working is a dot network domain name.

**Comment by darryllane** [comment]
All ive tried, do you mean an internal domain as in, on LAN?

**Comment by truesamurai** [comment]
no a public domain as in mydomainname.network

**Comment by darryllane** [comment]
It shouldn't make any difference, dns works in the same way regardless (as far as I am aware anyway). Hmm I'll keep an eye open for a domain to try reproduce the problem. Until I can reproduce the problem I can't help much.

**Comment by truesamurai** [comment]
yes true I was only thinking why the one domain does work and to other does not. and that are the only differences. thanks anyway. I will keep using the tool, its a great tool.

**Comment by darryllane** [comment]
👍
