### ISSUE TITLE
pdfminer error

### ISSUE THREAD

**Issue by LawDawe** [darryllane/Bluto#27]
hi im new to this all. im running python 3.8 

    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kahil\\AppData\\Local\\Temp\\pip-install-402_bmgc\\pdfminer\\setup.py'"'"'; __file__='"'"'C:\\Users\\kahil\\AppData\\Local\\Temp\\pip-install-402_bmgc\\pdfminer\\setup.py'"'"';f=getattr(tokeniz
e, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\kahil\AppData\Local\Temp\pip-install-402_bmgc\pdfminer\pip-egg-info'
         cwd: C:\Users\kahil\AppData\Local\Temp\pip-install-402_bmgc\pdfminer\
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\kahil\AppData\Local\Temp\pip-install-402_bmgc\pdfminer\setup.py", line 3, in <module>
        from pdfminer import __version__
      File "C:\Users\kahil\AppData\Local\Temp\pip-install-402_bmgc\pdfminer\pdfminer\__init__.py", line 5
        print __version__
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(__version__)?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by LawDawe** [comment]
ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kahil\\AppData\\Local\\Temp\\pip-install-402_bmgc\\pdfminer\\setup.py'"'"'; __file__='"'"'C:\\Users\\kahil\\AppData\\Local\\Temp\\pip-install-402_bmgc\\pdfminer\\setup.py'"'"';f=getattr(tokeniz
e, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\kahil\AppData\Local\Temp\pip-install-402_bmgc\pdfminer\pip-egg-info'
         cwd: C:\Users\kahil\AppData\Local\Temp\pip-install-402_bmgc\pdfminer\
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\kahil\AppData\Local\Temp\pip-install-402_bmgc\pdfminer\setup.py", line 3, in <module>
        from pdfminer import __version__
      File "C:\Users\kahil\AppData\Local\Temp\pip-install-402_bmgc\pdfminer\pdfminer\__init__.py", line 5
        print __version__
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(__version__)?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by LawDawe** [comment]
sorry misclicked close, didnt copy this line before

Collecting pdfminer==20140328
  Using cached https://files.pythonhosted.org/packages/57/4f/e1df0437858188d2d36466a7bb89aa024d252bd0b7e3ba90cbc567c6c0b8/pdfminer-20140328.tar.gz

**Comment by LawDawe** [comment]
got it.  i downloaded the hard copy

of pdfminer C:\Users\kahil\AppData\Local\Temp\pip-install-402_bmgc\pdfminer\pdfminer_init_.py
edited the "_init_.py"  and put brackets around "_version_"  

#!/usr/bin/env python
__version__ = '20140328'

if __name__ == '__main__':
    print (__version__)

then cmd - cd  C:\Users\kahil\Desktop\pdfminer-20140328

then cmd - python setup.py install 

then re ran pip3 install bluto 

install successfully

**Comment by darryllane** [comment]
You need to run this version of Bluto in python 2.7.x

**Comment by LawDawe** [comment]
> You need to run this version of Bluto in python 2.7.x

Thought that might be the case, there isn't anything for python3 yet? For bluto,

Strange though right? That i was still able to install it correctly after making that change? Havent run it yet but it said it was happy with the install

**Comment by darryllane** [comment]
Yeah it wont work properly, the libs are python 2 and so is the base code. Yes I do have a bluto 3 in the making, but its not ready for release yet. There is a taster of it in the dev branch

**Comment by LawDawe** [comment]
No worries, cant wait till its released, good luck, and keep up the good work

**Comment by darryllane** [comment]
Thank you
