### ISSUE TITLE
Unable to install Bluto after Git Clone,

### ISSUE THREAD

**Issue by jobydon** [darryllane/Bluto#29]
I am unable to install Bluto after git clone. 

Commands used are as follows - Linux/Debian

sudo git clone https://github.com/darryllane/Bluto.git
curl https://bootstrap.pypa.io/get-pip.py -o - | python
sudo pip install bluto -- command not found
cd Bluto
Bluto -- command not found
cd Bluto
tried Bluto - command not found.

Please suggest any command which can enable to install Bluto

**Comment by darryllane** [comment]
Hi can you let me know what version of Linux you are trying to install on?

Are you getting any errors during the install?

**Comment by arcillus** [comment]
Hey, I have a same problem.
it's said "

    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r_0qyrhj/pdfminer/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r_0qyrhj/pdfminer/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-r_0qyrhj/pdfminer/pip-egg-info                                       
         cwd: /tmp/pip-install-r_0qyrhj/pdfminer/                             
    Complete output (8 lines):                                                
    Traceback (most recent call last):                                        
      File "<string>", line 1, in <module>                                    
      File "/tmp/pip-install-r_0qyrhj/pdfminer/setup.py", line 3, in <module> 
        from pdfminer import __version__                                      
      File "/tmp/pip-install-r_0qyrhj/pdfminer/pdfminer/__init__.py", line 5  
        print __version__                                                     
                        ^                                                     
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(__version__)?                                                                   
    ----------------------------------------                                  
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.                

OS type(Kali)

**Comment by darryllane** [comment]
You are using Python3, try using Python 2

**Comment by darryllane** [comment]
pip or pip2 NOT pip3

**Comment by arcillus** [comment]
> pip or pip2 NOT pip3

Thank You... 
But it still happen. And I already found the problems. its my python that broke.

**Comment by Cybertail** [comment]
> > pip or pip2 NOT pip3
> 
> Thank You...
> But it still happen. And I already found the problems. its my python that broke.

Please how did you fix this.

**Comment by EroroData** [comment]
> > > pip or pip2 NOT pip3
> > 
> > 
> > Thank You...
> > But it still happen. And I already found the problems. its my python that broke.
> 
> Please how did you fix this.

Either you reinstall your python or install pip. Sometimes people have python but not pip.

**Comment by darryllane** [comment]
What OS are you using?
