### ISSUE TITLE
trouble installing

### ISSUE THREAD

**Issue by yazad123** [darryllane/Bluto#30]
Using cached https://files.pythonhosted.org/packages/57/4f/e1df0437858188d2d36466a7bb89aa024d252bd0b7e3ba90cbc567c6c0b8/pdfminer-20140328.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-10eam1hp/pdfminer/setup.py", line 3, in <module>
        from pdfminer import __version__
      File "/tmp/pip-install-10eam1hp/pdfminer/pdfminer/__init__.py", line 5
        print __version__
                        ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(__version__)?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-10eam1hp/pdfminer/

this is the final part of the install script i keep trying to change it and put the parantheses on the print __version__ but it doesn't let me 

help please thanks... im using 64bit kali linux and i write pip3 install Bluto as the command

**Comment by yazad123** [comment]
i fixed it by installing pip and doing pip install Bluto.....i'm new to this, but curious why was pip3 not compatible ?

**Comment by darryllane** [comment]
No this version of bluto is 2.7.x so just pip not pip3. Glad you got it working, anymore questions feel free to post

**Comment by yazad123** [comment]
thanks for the response man ...must be cool to program like that
