### ISSUE TITLE
CLI is incompatible with Python 3

### ISSUE THREAD

**Issue by jayvdb** [darryllane/Bluto#32]
https://github.com/darryllane/Bluto/blob/master/Bluto/bluto#L97 uses old Python 2 print syntax.

**Comment by darryllane** [comment]
Yes it's written in python 2.7.

**Comment by jayvdb** [comment]
Python 2.7 is no longer supported. ;-(

**Comment by darryllane** [comment]
I know, there is a 3.7 version in the wind but I need to make time to finish it.
