### ISSUE TITLE
Can't install Bluto

### ISSUE THREAD

**Issue by KedarJoshi11** [darryllane/Bluto#33]
Hi, 

When I try to install bluto using **pip3 install bluto** command, it gives me a error message saying

File "/tmp/pip-install-5sthiks6/pdfminer/pdfminer/__init__.py", line 5
        print __version__
                        ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(__version__)?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-5sthiks6/pdfminer/

Things I've tried to make this work. 
1. pip3 install setuptools - Not necessary but still. 
2. pip3 install pdfminer

Please let me know if this can be resolved. Thanks a lot!

**Comment by darryllane** [comment]
This is not compatible with python3, it's python2

**Comment by KedarJoshi11** [comment]
Thanks for the quick response Darryll. I'll switch to Python 2 for this.

**Comment by darryllane** [comment]
No problem dude, let me know if you need any help
