### ISSUE TITLE
Exposed HIBP API Key

### ISSUE THREAD

**Issue by Sq00ky** [darryllane/Bluto#35]
Hey there Darryllane,
I'm creating an issue because I have noticed that you've left your Have I Been Pwned API key exposed on Github! Just a reminder that the API Access is paid and anyone can authenticate as you with your API key! I highly suggest you remove it ASAP!
~Sq00ky

**Comment by adrwh** [comment]
I've let Troy know so that he can monitor and block any unusual use

**Comment by darryllane** [comment]
I know it's in there, don't block it please. Yes I am aware anyone can use it.
