### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by jazibdawre** [darryllane/Bluto#36]
![image](https://user-images.githubusercontent.com/57258130/79039769-240f1080-7c01-11ea-8000-7fd96a778048.png)

I am running this in a virtual environment using python2.7, any help would be appreciated.

**Comment by darryllane** [comment]
Currently it doesn't support virtualenvs, however I believe there is a pull request to deal with this. I will attempt to test the changes and merge if appropriate. For now, it won't work in virtualenv

**Comment by darryllane** [comment]
Check issue 34, try those changes and see if it works.
