### ISSUE TITLE
The connection hit a timeout. Are you connected to the internet?

### ISSUE THREAD

**Issue by acerolahub** [darryllane/Bluto#38]
Hi, I'm currently on a Kali 2020 distro and when I run bluto with a domain name, I got `The connection hit a timeout. Are you connected to the internet?` whatever the domain name I entered.

**Comment by darryllane** [comment]
Are you behind any proxies? What type of network are you on? Business LAN or Uni or at your own place?

**Comment by darryllane** [comment]
Please post an update

**Comment by overflood** [comment]
Actually run into the same issues, when behind a VPN. What needs to be done to get it working behind a VPN?
