### ISSUE TITLE
Bluto is unable to install on kali 2020 

### ISSUE THREAD

**Issue by akhan76** [darryllane/Bluto#39]
Dear darryllane,
I am trying to install Bluto on kali 2020 (latest release) with python 3.8.2 and Pip 19.2.3.
Please help me how can I sort out this issue?
it gives me a lot of errors while installation.

**Comment by darryllane** [comment]
Current version of bluto does not support Python 3. It is python2.7.x

**Comment by dayfine** [comment]
`python -m pip install bluto`
