### ISSUE TITLE
Bluto hangs at Brute Forcing Sub-Domains

### ISSUE THREAD

**Issue by unraveller82** [darryllane/Bluto#40]
Hi, 

I been frequently experiencing hang while running Brute Forcing Sub-Domains. It will stop running at that stage. 

It used to work if i change my router WAN IP. However, its no longer working. Any advise?

**Comment by darryllane** [comment]
I've not seen this problem before. Can you let me know what your setup is please. Python version, bluto version, is version etc

**Comment by erwanlr** [comment]
Have the same issue, let it running for 2h before killing it ;p (latest version, 2.4.17).

Edit: Seems to happen when a wildcard is in place for the domain.

**Comment by unraveller82** [comment]
Hi Darryl,
my setup:
Bluto v2.4.17
Python 2.7.17
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2020.1
Codename:       kali-rolling

**Comment by unraveller82** [comment]
Hi Darryl,
I tried to reinstall bluto and now I am getting timed out message

_"None of the Name Servers are vulnerable to Zone Transfers

Testing For Wild Cards
The DNS operation timed out after 10.0107131004 seconds"_

**Comment by unraveller82** [comment]
Hi Darryl,

Its working now. I changed the VMware workstation player network setting from NAT to Bridged.

**Comment by darryllane** [comment]
It does take longer on wildcard domains but unless your using a custom list it shouldn't take that long. Ill need to find a wild carded domain to test on (with permission to of course).
