### ISSUE TITLE
print _version_ error 

### ISSUE THREAD

**Issue by athish-k** [darryllane/Bluto#41]
Hi Darryl,

I had experimented many ways to install the bluto, but no luck in my virtual machine.

Below is the details of the version installed on my machine.
Linux kali 5.5.0-kali2-amd64 #1 SMP Debian 5.5.17-1kali1 (2020-04-21) x86_64 GNU/Linux
Python 2.7.18 (default, Apr 20 2020, 20:30:41)
pip 20.1.1 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)
git version 2.27.0

Could you please help me to overcome on this error.

Thanks & Regards,
Athish
![bluto_error](https://user-images.githubusercontent.com/68858181/88549634-2b3a1d00-d03e-11ea-9673-754c0798db9c.PNG)

**Comment by darryllane** [comment]
Hi apologies on the delayed response, I haven't checked in for a while. The error your getting is because your using python 3.
