### ISSUE TITLE
getting error while installing

### ISSUE THREAD

**Issue by lazyscorpion** [darryllane/Bluto#42]
getting an error while installing through pip

root@kali:~# python -m pip install bluto
Collecting bluto
  Using cached Bluto-2.4.17.tar.gz (874 kB)
Requirement already satisfied: BeautifulSoup4 in /usr/lib/python3/dist-packages (from bluto) (4.8.2)
Requirement already satisfied: dnspython in /usr/lib/python3/dist-packages (from bluto) (1.16.0)
Collecting docopt
  Using cached docopt-0.6.2.tar.gz (25 kB)
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from bluto) (4.5.0)
Collecting oletools
  Using cached oletools-0.55.1.zip (3.1 MB)
Collecting pdfminer==20140328
  Using cached pdfminer-20140328.tar.gz (4.1 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-f5naygvt/pdfminer/setup.py'"'"'; __file__='"'"'/tmp/pip-install-f5naygvt/pdfminer/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-nb7w0np1                                             
         cwd: /tmp/pip-install-f5naygvt/pdfminer/                           
    Complete output (8 lines):                                              
    Traceback (most recent call last):                                      
      File "<string>", line 1, in <module>                                  
      File "/tmp/pip-install-f5naygvt/pdfminer/setup.py", line 3, in <module>                                                                           
        from pdfminer import __version__                                    
      File "/tmp/pip-install-f5naygvt/pdfminer/pdfminer/__init__.py", line 5
        print __version__                                                   
              ^                                                             
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(__version__)?                                                               
    ----------------------------------------                                
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by darryllane** [comment]
Your using python 3, you need to use python 2
