### ISSUE TITLE
Mac OS logger issue

### ISSUE THREAD

**Issue by Teicu** [darryllane/Bluto#43]
Hi Darryl  

any help to fix this issue? thank you

_bluto
Traceback (most recent call last):
  File "/usr/local/bin/bluto", line 18, in <module>
    from modules.logger_ import info, error
ImportError: No module named logger__ 

_pip install logger
Requirement already satisfied: logger in ./Library/Python/2.7/lib/python/site-packages (1.4)_

**Comment by darryllane** [comment]
Hey dude, what version of bluto and python are you using. I'll try recreate.
