### ISSUE TITLE
Bluto completely broken

### ISSUE THREAD

**Issue by samokosik** [darryllane/Bluto#47]
Hello, I installed Bluto using `pip install bluto`. It installed, but it is completely broken:
![image](https://user-images.githubusercontent.com/73645764/114274906-cafad800-9a20-11eb-9aed-a0f99664d298.png)
There are missing parentheses in print statements and even after they are being fixed, bluto still does not work.

Is there any chance I can get this going?
Thank you

**Comment by thebakedchef** [comment]
okay so I'm going through and fixing the code for shits and giggles while learning python for the first time, fixed all the parentheses and other syntax errors but cannot seem to fix this 
`Traceback (most recent call last):
  File "/usr/local/bin/bluto", line 48, in <module>
    from modules.get_dns import action_brute_start, action_wild_cards, action_zone_transfer, get_dns_details, action_brute_wild, set_resolver
  File "/usr/local/lib/python3.9/dist-packages/Bluto/modules/get_dns.py", line 11, in <module>
    import bluto_logging
ModuleNotFoundError: No module named 'bluto_logging'`
 if anyone can help figure this out it would be appriciated

**Comment by darryllane** [comment]
closed
