### ISSUE TITLE
import dns.resolver ImportError: No module named dns.resolver

### ISSUE THREAD

**Issue by AdvayCoder** [darryllane/Bluto#48]
Hello!  I am running Bluto but I get this error:

File "/usr/local/bin/bluto", line 43, in <module>
    import dns.resolver
ImportError: No module named dns.resolver
 
How do I fix this?  Thank you!

**Comment by darryllane** [comment]
Hi, what version of python are you running?

**Comment by AdvayCoder** [comment]
I am on the latest version of Kali Linux.  There I cannot run just the "bluto" command because it defaults to running python 3.  I ran the command "python /usr/local/bin/bluto" and it gave me this error.  When I run the command "python" I am running version 2.7.18.

**Comment by AdvayCoder** [comment]
Is there a solution?

**Comment by darryllane** [comment]
Well the simple answer is to install the missing lib. Pip install 'libname'
but a better approach is for me to try recreate the issue and build a fix
if needs be. So if you can let me know how you installed it I'll try take a
look tonight

**Comment by AdvayCoder** [comment]
Ok.  Here is what I did on Kali Linux:

I ran "sudo pip install bluto"

Then, once it installed, I ran "python /usr/local/bin/bluto" (Since just running "bluto" makes it run in python 3, and gives other errors).

It then gives me the error, which is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Bluto/bluto", line 43, in <module>
    import dns.resolver
ImportError: No module named dns.resolver


I made an alias called "bluto" that makes it run the python2 bluto command above in .zshrc.  Thank you for taking the time to fix the issue!

**Comment by AdvayCoder** [comment]
Is there a solution?

**Comment by darryllane** [comment]
I'm guessing when it installed it didn't install fully in python2. Try this using pip for python2, sudo pip install dnspython

**Comment by AdvayCoder** [comment]
I installed dnspython, but it installed to the python 3 lib, so I moved it to the python 2.7 dist-packages in /usr/local/lib/python2.7/dist-packages/, and then I ran the command "bluto" (correctly aliased to run the command in python 2).  I ran it again, but it gives the same error, meaning that it cannot import it correctly.  Do I need to move it into the "Bluto" folder, somewhere else inside that folder, or in '/usr/bin/bin/bluto'?  Sorry, I am new to python so I am not sure where the dnspython folder needs to be.  Thank you!

**Comment by darryllane** [comment]
Moving the python3 install into the python 2 distro won't work. You need to install with pip2.x

**Comment by AdvayCoder** [comment]
When I do "sudo pip install dnspython" it says "Requirement already satisfied: dnspython in /usr/lib/python3/dist-packages (2.0.0)", which means that it "pip" is installing to python3 instead of python 2, just like "pip3".

**Comment by nathanzebedee** [comment]
Yo, I have the same issue. Ever figure it out?

**Comment by darryllane** [comment]
I'd uninstall it and install it correctly. Or install the lib correctly
rather than shifting it around.

**Comment by nathanzebedee** [comment]
How would you “install it correctly” exactly?

**Comment by darryllane** [comment]
Install it as you did but with python 2.x

**Comment by getJobLength** [comment]
But how would you do that since pip2 is no longer in kali. Atleast not in my version of kali.

**Comment by darryllane** [comment]
Hi, I'd suggest googling how to install pip2 and python 2.7 on Kali.
