### ISSUE TITLE
ile "/usr/local/bin/bluto", line 97 print title ^ SyntaxError: Missing parentheses in call to 'print'. Did you mean print(title)?.This is what i can see while start bluto in my kali.Is anyone know any alternative solution please let  me know

### ISSUE THREAD

**Issue by anoopvijayan112** [darryllane/Bluto#49]

**Comment by darryllane** [comment]
Seems like your running it with python 3.x

**Comment by anoopvijayan112** [comment]
> Seems like your running it with python 3.x

thank you for the reply sir.yes sir i am running python 3 on my kali..could you tell me the compactable version of bluto and python..also the command to install please.

**Comment by darryllane** [comment]
It's not compatible with python 3. It's a python 2 app

**Comment by anoopvijayan112** [comment]
then i need to remove python3 and and install python 2.is it ok?

**Comment by darryllane** [comment]
Correct, bluto is in need of updating but I don't have the time. I might one day release a new version

**Comment by anoopvijayan112** [comment]
> Correct, bluto is in need of updating but I don't have the time. I might one day release a new version







ok sir thank you for the response i will do...

**Comment by darryllane** [comment]
close
