### ISSUE TITLE
Compromised Account Output

### ISSUE THREAD

**Issue by d0s1nt** [darryllane/Bluto#5]
It would be useful if you could dump the compromised accounts within the terminal, tab delimited like the rest of the dumps.

Cheers,

**Comment by darryllane** [comment]
Will add it

**Comment by darryllane** [comment]
Try uninstalling and reinstalling with

sudo pip install git+git://github.com/darryllane/Bluto/@feature-compro-add

**Comment by darryllane** [comment]
Changes have been pushed to master.
