### ISSUE TITLE
Needs Python3 Update

### ISSUE THREAD

**Issue by iamtecheater** [darryllane/Bluto#50]
Please update this to python3 as I have to go in and change all the files to be updated which should not be the case.
Thanks

**Comment by darryllane** [comment]
Hiya, yeah it's been on the cards a long time. I did start a revamp including GUI html reporting but just never finished it. Hopefully I can find the time at some point. And new features.

**Comment by arturs706** [comment]
Hi
Can you please convert this to Python3 if possible?
I cannot run this on Kali
