### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by cybercor3** [darryllane/Bluto#51]
Hello!
So I managed to install using (sudo pip3 install git+git://github.com/darryllane/Bluto@dev) and when I execute bluto command I get this:
Traceback (most recent call last):
  File "/usr/local/bin/bluto", line 18, in <module>
    from modules.logger_ import info, error
ModuleNotFoundError: No module named 'modules'

  

What should I do?
Thank you!

**Comment by darryllane** [comment]
Did you particularly want the Dev branch? Also what os are you running?

**Comment by cybercor3** [comment]
I am running on Kali Linux on VB and I choose the Dev branch because when I try to do sudo pip2 install bluto I get:

ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-RRCRU4/bluto/setup.py'"'"'; __file__='"'"'/tmp/pip-install-RRCRU4/bluto/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-76JSNf               
         cwd: /tmp/pip-install-RRCRU4/bluto/                                       
    Complete output (10 lines):                                                    
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'include_package_data'                                                        
      warnings.warn(msg)                                                           
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'                                                            
      warnings.warn(msg)                                                           
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]          
       or: setup.py --help [cmd1 cmd2 ...]                                         
       or: setup.py --help-commands                                                
       or: setup.py cmd --help                                                     
                                                                                   
    error: invalid command 'egg_info'                                              
    ----------------------------------------                                       
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by darryllane** [comment]
Odd, let me know which release of Kali and I'll try recreate the issue.

**Comment by cybercor3** [comment]
cat /etc/os-release-
VERSION="2021.3"
VERSION_ID="2021.3"

uname -a           
Linux kali 5.10.0-kali9-amd64 #1 SMP Debian 5.10.46-4kali1 (2021-08-09) x86_64 GNU/Linux

**Comment by jriseley** [comment]
Just chiming in, I also had this error when installing from dev like so:

pip install git+git://github.com/darryllane/Bluto@dev

Results in:

  File "/home/blah/venv/py37venv/bin/bluto", line 18, in <module>
    from modules.logger_ import info, error
ModuleNotFoundError: No module named 'modules'

 It's in a venv with python 3.7.5 on Ubuntu 20.04.

I don't particularly need the dev branch, I'm just adding my vote for this error.

**Comment by tlgz** [comment]
┌──(root💀kali)-[/]
└─# bluto      
Traceback (most recent call last):
  File "/usr/local/bin/bluto", line 18, in <module>
    from modules.logger_ import info, error
ModuleNotFoundError: No module named 'modules'
 
how to fix? running latest kali linux

**Comment by Huangdi-599** [comment]
> ┌──(rootskullkali)-[/] └─# bluto Traceback (most recent call last): File "/usr/local/bin/bluto", line 18, in from modules.logger_ import info, error ModuleNotFoundError: No module named 'modules'
> 
> how to fix? running latest kali linux

try installing pip2 using "sudo apt-get install python-pip" (do this if you have python2.7 installed already)
then  run "sudo pip2 install  bluto"
then you can run bluto



if you are still receiving an error after this, try removing python3,  then go through the process again

**Comment by darryllane** [comment]
I wouldn't install from dev, I've not looked at it for quite some time. I'll remove the branch. Please use the main branch

**Comment by biawaklaut** [comment]
Hello, I have another issue with installation:

Collecting bluto
  Using cached Bluto-2.4.17.tar.gz (874 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: BeautifulSoup4 in /usr/lib/python3/dist-packages (from bluto) (4.11.1)
Requirement already satisfied: dnspython in /usr/lib/python3/dist-packages (from bluto) (2.2.0)
Requirement already satisfied: docopt in /usr/lib/python3/dist-packages (from bluto) (0.6.2)
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from bluto) (4.8.0)
Collecting oletools
  Using cached oletools-0.60-py2.py3-none-any.whl (968 kB)
Collecting pdfminer==20140328
  Using cached pdfminer-20140328.tar.gz (4.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8crojcsl/pdfminer_56e7c1d762d54f9399edf1bb3b11d959/setup.py", line 3, in <module>
          from pdfminer import __version__
        File "/tmp/pip-install-8crojcsl/pdfminer_56e7c1d762d54f9399edf1bb3b11d959/pdfminer/__init__.py", line 5
          print __version__
                ^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(__version__)?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Sorry, I just learned how to use Kali Linux, here's my Kali Linux version

PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2022.1"
VERSION_ID="2022.1"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian

Thank you very much

**Comment by darryllane** [comment]
It's a python 2 tool
