### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(title)?

### ISSUE THREAD

**Issue by ghost** [darryllane/Bluto#52]
Hello,

I have an issue that does not allow me to execute bluto.

The issue message is: 

`debian@mysite:~$ bluto
  File "/usr/local/bin/bluto", line 97
    print title
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(title)?
debian@mysite:~$`

-----

To install Bluto I followed these steps:

`curl https://bootstrap.pypa.io/get-pip.py -o - | python3` (note : vs python)

`sudo pip install bluto`

-----

So I tried to update by executing this line `sudo pip install bluto --upgrade`

I have the following error message:

`error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nfnppyy8/pdfminer_b6cb60f3b146472abdcede512023d5af/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nfnppyy8/pdfminer_b6cb60f3b146472abdcede512023d5af/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-j6lzccmf
       cwd: /tmp/pip-install-nfnppyy8/pdfminer_b6cb60f3b146472abdcede512023d5af/
  Complete output (8 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-nfnppyy8/pdfminer_b6cb60f3b146472abdcede512023d5af/setup.py", line 3, in <module>
      from pdfminer import __version__
    File "/tmp/pip-install-nfnppyy8/pdfminer_b6cb60f3b146472abdcede512023d5af/pdfminer/__init__.py", line 5
      print __version__
            ^
  SyntaxError: Missing parentheses in call to 'print'. Did you mean print(__version__)?
  ----------------------------------------`

Is there something I did wrong? What ?
Any ideas ?
Thanks for your help.
Regards
Christophe.

**Comment by darryllane** [comment]
It's python2 app

**Comment by ghost** [comment]
Hello Darryl,
Thanks for your feedback.

when I run this line `curl https://bootstrap.pypa.io/get-pip.py -o - | python2`
I have this message `This script does not work on Python 2.7 The minimum supported Python version is 3.6.`

when I run this line `curl https://bootstrap.pypa.io/get-pip.py -o - | python`
I have this message `curl: (23) Failure writing output to destination`

I look forward to being able to use your program. I got to know him in a book on ethical hacking.
Regards,
Christophe.

**Comment by darryllane** [comment]
Using python2, do 

Pip install bluto

**Comment by ghost** [comment]
Hi Darryl,

Just to inform you of the installation sequence (a little different from the one shown) that works

`root@mysite:/$ apt-get purge --auto-remove python3.9`

`root@mysite:/$ apt install python`
`root@mysite:/$ python --version`
`Python 2.7.18`

`root@mysite:/$ curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o - | python` (> important difference)

`root@mysite:/$ pip install bluto`

Regards,
Christophe.

**Comment by darryllane** [comment]
Great glad you've got it working
