### ISSUE TITLE
python2.7 compatibility

### ISSUE THREAD

**Issue by Ayman-Rayan** [darryllane/Bluto#53]
hey i know the problem going on with the compatibility of the tool 
but can you tell me how to run it on python2.7 
i got python3.9 and 2.7 installed on my virtual linux machine 
i used update-version command and gave the priority to /usr/bin/python2.7 
but whenever i use pip install bluto it still goes to /python3.9 and generates errors and warnings due to incompatibility .

**Comment by UltimateBohab** [comment]
use a virtualenv run it from there
