### ISSUE TITLE
download error.

### ISSUE THREAD

**Issue by tlgz** [darryllane/Bluto#55]
┌──(root💀kali)-[/]
└─# bluto
Traceback (most recent call last):
File "/usr/local/bin/bluto", line 18, in
from modules.logger_ import info, error
ModuleNotFoundError: No module named 'modules'

how to fix? running latest kali linux
i used the pip download and i have latest pip downloaded

**Comment by darryllane** [comment]
Hi, it's a python 2.7.x tool, it won't work with python 3.

**Comment by tlgz** [comment]
how could i use it then? ty for your reply

**Comment by darryllane** [comment]
Run it with python 2.7.x
