### ISSUE TITLE
Bulto is not installed

### ISSUE THREAD

**Issue by Jainam2505** [darryllane/Bluto#57]
Dear darryllane,
I am trying to install Bluto on kali (the latest release) with Python 2.7.18 
I got the issue like 

`┌──(durk㉿durk)-[~]
└─$ bluto                                                                   1 ⨯
  File "/usr/local/bin/bluto", line 97
    print title
    ^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
`
[screen shot of that issue
](https://docs.google.com/document/d/1Efw-38zL0hl5QvFcG914dPShOz9xqeBbKm6_jMgVMiQ/edit?usp=sharing)]

Please help me with how can I sort out this issue?
I also got the same error with sudo command

**Comment by darryllane** [comment]
Can you screenshot the error please

**Comment by Jainam2505** [comment]
please click on that screenshot line, this is the link i have added the 2 screen shot over there.

**Comment by darryllane** [comment]
Looks like a python 3 error, make sure python 2 is installed and run pip install bluto (pip 2)
