### ISSUE TITLE
Use HTTPS for freegeoip

### ISSUE THREAD

**Issue by ethicalhack3r** [darryllane/Bluto#6]
https://github.com/darryllane/Bluto/blob/dcd0158d5b1fccf69a88ada4301c61b01ebe8695/Bluto/modules/general.py#L88

https://github.com/darryllane/Bluto/blob/dcd0158d5b1fccf69a88ada4301c61b01ebe8695/Bluto/modules/general.py#L93

**Comment by ethicalhack3r** [comment]
And Bing https://github.com/darryllane/Bluto/blob/8ed95c39246b0bfb8d24a843ef3c655774e658ac/Bluto/modules/search.py#L218 :)

Google: https://github.com/darryllane/Bluto/blob/8ed95c39246b0bfb8d24a843ef3c655774e658ac/Bluto/modules/general.py#L156

Your own site: https://github.com/darryllane/Bluto/blob/8ed95c39246b0bfb8d24a843ef3c655774e658ac/Bluto/modules/general.py#L166

**Comment by darryllane** [comment]
They were moved to https but then removed as it was causing errors. Will look into again

**Comment by darryllane** [comment]
freegeoip added, will be leaving the others as is for now
