### ISSUE TITLE
I am operating kali linux as a virtual machine and i am using the 2022 version which definitely have python3 installed

### ISSUE THREAD

**Issue by beautifullymade** [darryllane/Bluto#63]
i keep getting this errors when i try to install bluto on my VM 

Collecting bluto
  Using cached Bluto-2.4.17.tar.gz (874 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: BeautifulSoup4 in /usr/lib/python3/dist-packages (from bluto) (4.11.1)
Requirement already satisfied: dnspython in /usr/lib/python3/dist-packages (from bluto) (2.2.0)
Requirement already satisfied: docopt in /usr/lib/python3/dist-packages (from bluto) (0.6.2)
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from bluto) (4.8.0)
Collecting oletools
  Using cached oletools-0.60.1-py2.py3-none-any.whl (977 kB)
Collecting pdfminer==20140328
  Using cached pdfminer-20140328.tar.gz (4.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-lty35tm7/pdfminer_6184f9010af3406696204f3bcb63612e/setup.py", line 3, in <module>
          from pdfminer import __version__
        File "/tmp/pip-install-lty35tm7/pdfminer_6184f9010af3406696204f3bcb63612e/pdfminer/__init__.py", line 5
          print __version__
          ^^^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

can you please tell me how to resolve this issue?
you can contact me personally on my email... mr.gerhard@outlook.com
thank you!!!

**Comment by darryllane** [comment]
It's a python 2.7.x app
