### ISSUE TITLE
NameError: name 'path' is not defined

### ISSUE THREAD

**Issue by shaulzak** [darryllane/Bluto#64]
/Users/dev/Bluto/.venv/bin/python /Users/ShaulZ/dev/Bluto/Bluto/bluto -api 2b0ab19df982a783877a6b59b982fdba4b6c3669 
Traceback (most recent call last):
  File "/Users/dev/Bluto/Bluto/bluto", line 57, in <module>
    FILENAME_1 = path + "/Bluto/doc/subdomains-top1mil-20000.txt"
NameError: name 'path' is not defined

**Comment by darryllane** [comment]
Install via pip

Follow the instructions
