### ISSUE TITLE
Remove .DS_Store

### ISSUE THREAD

**Issue by ethicalhack3r** [darryllane/Bluto#7]
https://github.com/darryllane/Bluto/blob/8ed95c39246b0bfb8d24a843ef3c655774e658ac/Bluto/modules/.DS_Store

Would add it to gitignore file too :)

**Comment by darryllane** [comment]
Hmm its already in gitignore so not sure what happen here. Will take a look at the setup.py, could have been due to the merge from dev branch (not having ignore).

**Comment by darryllane** [comment]
Ive looked through both branches and cant find any .DS_Store files. Checked the release package too. Also checked the `MANIFEST.in`, that contains:

> include *.txt
> include *.md
> recursive-include Bluto *.txt *.py
> recursive-include Bluto/doc *.txt *.py
> recursive-include Bluto/doc/modules *.txt *.py
> recursive-include Bluto/log *.log
> recursive-exclude *.DS_store

The `setup.py` file doesn't seem to have any oddities that I can find, let alone anything that could explain the nocuous `.DS_store` files lol. I'm not the brightest so please excuse the debuious question, but how did you find, for lack of better word, that `branch`?

**Comment by ethicalhack3r** [comment]
You mean the file location? Its in this dir https://github.com/darryllane/Bluto/tree/master/Bluto/modules

**Comment by darryllane** [comment]
Done :)
