### ISSUE TITLE
Assign a new flag for entering the domain to be scanned (-D) and output the results (-R) in a .txt format with a custom wordlist (-W)

### ISSUE THREAD

**Issue by anshumanbh** [darryllane/Bluto#8]
Example:

bluto -D xyz.com -W /tmp/wordlist.txt -R /tmp/results.txt

**Comment by anshumanbh** [comment]
The results.txt would look something like:

www.xyz.com
test.xyz.com
staging.xyz.com

....so on and so forth..

**Comment by darryllane** [comment]
ok and this would forego any of the other tests, would only brute force and output contents to a txt file?

**Comment by anshumanbh** [comment]
yes precisely! I am only looking to automate bruteforcing of subdomains and not perform other OSINT tasks hence this request :)

**Comment by darryllane** [comment]
Hmm well ill write you a function that does it in parallels. Ill take a look this weekend

**Comment by darryllane** [comment]
Dude can you let me know your git page please?

**Comment by anshumanbh** [comment]
github.com/anshumanbh

**Comment by darryllane** [comment]
Cool will tey get it written this weekend for you.

**Comment by darryllane** [comment]
Dude which repo do you want this in? Happy to write the function for you but need to know where to add it.

**Comment by anshumanbh** [comment]
https://github.com/anshumanbh/Bluto

**Comment by darryllane** [comment]
dude make a blank repo and ill write you a standalone bruteforcer with the functionality you want. I dont want to write it and upload to the repo you said as it wont be bluto. It will be its own thing

**Comment by anshumanbh** [comment]
It's all right. I really appreciate you trying to help me and I understand it is difficult to take time out :). But, I have what I need now. Check out - https://github.com/anshumanbh/brutesubs. This is what I was trying to do and I was hoping I could include Bluto but at this point, I think there is no need.
